name: Despliegue Automático en DigitalOcean

on:
  push:
    branches:
      - main  # OJO: Si tu rama principal se llama 'master', cámbialo aquí.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar por SSH y actualizar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /root/my-portfolio-backend
            git pull origin main
            docker compose up -d --build